Repository nplay-team/moderation-bot, pull requests merged in 2025-03, with the labels that each got.

#39 [FIX] Message purge commands fails if amount=1
  src/main/java/de/nplay/moderationbot/moderation/commands/BulkDeleteCommands.java
Labels: t:bug, s:completed, p:low

#35 [FEATURE] Config System
  embeds.json
  src/main/java/de/nplay/moderationbot/config/ConfigCommands.java
  src/main/java/de/nplay/moderationbot/config/ConfigService.java
  src/main/java/de/nplay/moderationbot/config/bot/BotConfig.java
  src/main/java/de/nplay/moderationbot/serverlog/Serverlog.java
  src/main/java/de/nplay/moderationbot/serverlog/channel/ServerlogChannelCommands.java
  src/main/java/de/nplay/moderationbot/serverlog/channel/ServerlogChannelService.java
  src/main/resources/database/postgresql/1/patch_5.sql
  src/main/resources/database/version
Labels: t:feature, s:completed, p:low

#37 [FEATURE] Spielersuche-Auschluss
  embeds.json
  src/main/java/de/nplay/moderationbot/embeds/EmbedHelpers.java
  src/main/java/de/nplay/moderationbot/moderation/ModerationUtils.java
  src/main/java/de/nplay/moderationbot/moderation/create/ModerationActBuilder.java
  src/main/java/de/nplay/moderationbot/moderation/create/ModerationCommands.java
  src/main/java/de/nplay/moderationbot/moderation/modlog/ModlogCommand.java
  src/main/java/de/nplay/moderationbot/serverlog/ModerationEvents.java
  src/main/java/de/nplay/moderationbot/spielersuche/ausschluss/SpielersucheAusschlussCommands.java
Labels: t:feature, s:completed, p:low

#42 [FEATURE] Added notes embed to modlog chain
  src/main/java/de/nplay/moderationbot/moderation/modlog/ModlogCommand.java
Labels: t:feature, s:completed, p:low

#40 fix modlog failing for non-guild users
  src/main/java/de/nplay/moderationbot/embeds/EmbedHelpers.java
  src/main/java/de/nplay/moderationbot/moderation/ModerationService.java
  src/main/java/de/nplay/moderationbot/moderation/modlog/ModlogCommand.java
  src/main/java/de/nplay/moderationbot/rules/RuleService.java
Labels: t:improvement, s:completed, p:low
